### ISSUE TITLE
mp3 files in library marked as missing

### ISSUE THREAD

**Issue by linuxrider** [flathub/org.gnome.Rhythmbox3#16]
As of the latest update to verison 3.4.3 and runtime 3.30 all mp3 files are marked as missing.
They can be played when opened from nautilus.
Switching back to the previous commit 3f48da15eac0b4c8195317f49b53b9a05ce69280d37dff6598683035e8b4eef7 brings them back.
m4a files are unaffected by this issue.

Could this be related to the removal of gmime?

**Comment by hadess** [comment]
> As of the latest update to verison 3.4.3 and runtime 3.30 all mp3 files are marked as missing.
> They can be played when opened from nautilus.
> Switching back to the previous commit 3f48da15eac0b4c8195317f49b53b9a05ce69280d37dff6598683035e8b4eef7 brings them back.
> m4a files are unaffected by this issue.

I saw this problem as well, but it disappeared after nuking my Rhythmbox library and starting again. Probably not something you'd want to do, but the fact that m4a file aren't affected is useful.

> Could this be related to the removal of gmime?

Absolutely not.

Can you attach a copy of `~/.var/app/org.gnome.Rhythmbox3/data/rhythmbox/rhythmdb.xml` to this bug?

**Comment by linuxrider** [comment]
Find attached the zipped rhythmdb.xml.
[rhythmdb.zip](https://github.com/flathub/org.gnome.Rhythmbox3/files/2786719/rhythmdb.zip)

**Comment by hadess** [comment]
Short version, this will work around the problem:
```
flatpak run --env=GIO_USE_VOLUME_MONITOR=unix org.gnome.Rhythmbox3
```

Long version, I reproduced this, and it has nothing to do with MP3s, and the only reason why MP4 files might not be affected is that they weren't indexed to start with, as there was no MPEG-4 support.

With the old Rhythmbox, no AAC/MP4 support:
```
Rhythmbox-Message: Missing plugin: gstreamer|1.0|rhythmbox-metadata|MPEG-4 AAC decoder|decoder-audio/mpeg, mpegversion=(int)4, level=(string)2, base-profile=(string)lc, profile=(string)lc
```

The problem is caused by the new gvfs access support, which triggers a bug in Rhythmbox. Before we had access to gvfs, the mounts list would have looked something like:
```
$ GIO_USE_VOLUME_MONITOR=unix gio mount -li
<snip>
Mount(2): Music -> file:///home/hadess/Music
  Type: GUnixMount
  default_location=file:///home/hadess/Music
  themed icons:  [drive-harddisk]
  symbolic themed icons:  [drive-harddisk-symbolic]
  can_unmount=1
  can_eject=0
  is_shadowed=0
```

So rhythmbox indexed everything in ~/Music, and set a mountpoint for it:
```
<?xml version="1.0" standalone="yes"?>
<rhythmdb version="2.0">
  <entry type="ignore">
<snip>
    <mountpoint>file:///home/hadess/Music</mountpoint>
<snip>
  </entry>
```

And then, after the upgrade:
```
$ gio mount -li
<snip, no Music mounted>
```

Then, when started, Rhythmbox will throw:
```
(16:34:55) [0x5566b5fae520] [perform_next_mount] rhythmdb.c:917: mounting file:///home/hadess/Music
(16:34:55) [0x5566b5fae520] [perform_next_mount_cb] rhythmdb.c:891: Unable to mount file:///home/hadess/Music: volume doesn’t implement mount
(16:34:55) [0x5566b5fae520] [perform_next_mount] rhythmdb.c:908: finished mounting
```
and because the file's mountpoint is not listed in `db->priv->active_mounts`, then it's considered missing until that mount point appears, which it never will...

**Comment by hadess** [comment]
Bug filed upstream:
https://gitlab.gnome.org/GNOME/rhythmbox/issues/1689
